"""Centralized application configuration.

Collects every environment variable the running application reads (server
bind settings, CORS, database, agent skill store, LLM selection, admin
bootstrap, secret encryption, HashiCorp Vault, MCP registry, and session
auth) into a single :class:`Settings` model instead of scattered
``os.getenv`` calls. Values with side-effecting fallback behavior (random
admin password generation, Fernet key generation/persistence) are left to
the modules that own that behavior; this model only resolves the plain
configuration value.

``scripts/export_openapi.py``'s ``OPENAPI_OUTPUT`` is intentionally excluded:
that script is a standalone dev-time CLI tool outside the running
application, and keeps reading its own environment variable directly.
"""

from functools import lru_cache
from pathlib import Path
from typing import Annotated, Any

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, NoDecode, SettingsConfigDict

#: Fallback sliding idle timeout (8 hours) used when
#: ``SESSION_IDLE_TIMEOUT_SECONDS`` is unset or not a valid integer.
_DEFAULT_IDLE_TIMEOUT_SECONDS = 28800

#: How long (1 hour) a published skill revision directory is kept from pruning
#: regardless of whether anything references it. A workflow run reads the
#: skill's current ``commit_sha`` and inserts its WorkflowSession row a moment
#: later; the grace window covers that gap, so a concurrent pull cannot delete
#: the revision the run just picked before the row naming it exists.
_DEFAULT_PRUNE_GRACE_SECONDS = 3600


class Settings(BaseSettings):
    """Typed, environment-driven application configuration.

    Fields are populated from process environment variables (matched
    case-insensitively by name) or, when unset, from ``backend/.env``.

    Attributes:
        host: Uvicorn bind host, used only by ``main.py``'s ``__main__`` block.
        port: Uvicorn bind port, used only by ``main.py``'s ``__main__`` block.
        reload: Whether that same ``__main__`` block enables uvicorn autoreload.
        cors_origins: Allowed CORS origins for the API.
        db_url: Database URL selecting SQLite (default) or PostgreSQL.
        skills_dir: Root of the Agent Skill store, laid out as
            ``<skill_id>/<commit_sha>/``. This is durable state, not a cache:
            a WorkflowSession pins the revision it started with, so wiping the
            directory leaves existing sessions unable to load their skill until
            an admin pulls again. In a horizontally scaled deployment it must
            be a volume shared by every replica.
        skills_prune_grace_seconds: How long an unreferenced skill revision
            directory is kept before a pull may prune it.
        llm_model: LLM selection, either a bare Gemini model name or a
            ``litellm:<provider>/<model>`` string.
        role_description: Base role text fed into the system prompt builder.
        admin_password: Password for the seeded initial ``admin`` user; a
            random password is generated by ``bootstrap.py`` when unset.
        secret_encryption_key: Fernet key for encrypting local secrets
            (first in the resolution precedence handled by ``secret_cipher.py``).
        secret_key_file: Path to the on-disk Fernet key file (second in that
            precedence).
        vault_addr: HashiCorp Vault server address; Vault is disabled when unset.
        vault_role_id: AppRole authentication role id.
        vault_secret_id: AppRole authentication secret id.
        vault_approle_mount: AppRole login mount path.
        vault_token: Static Vault token, used when AppRole credentials are absent.
        mcp_registry_url: Base URL of the official MCP registry.
        session_cookie_secure: Whether auth/CSRF cookies carry the ``Secure``
            attribute.
        session_idle_timeout_seconds: Sliding idle timeout, in seconds, for a
            login session.
    """

    model_config = SettingsConfigDict(
        env_file=str(Path(__file__).resolve().parent / ".env"),
        env_file_encoding="utf-8",
        extra="ignore",
    )

    host: str = "0.0.0.0"
    port: int = 8000
    reload: bool = False

    cors_origins: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: ["http://localhost:3000"]
    )

    db_url: str = "sqlite:///a2flow.db"

    skills_dir: Path = Field(
        default_factory=lambda: Path(__file__).resolve().parent / ".skills"
    )
    skills_prune_grace_seconds: int = _DEFAULT_PRUNE_GRACE_SECONDS

    llm_model: str = "gemini-2.0-flash"
    role_description: str = "You are a helpful assistant."

    admin_password: str | None = None

    secret_encryption_key: str | None = None
    secret_key_file: Path | None = None

    vault_addr: str | None = None
    vault_role_id: str | None = None
    vault_secret_id: str | None = None
    vault_approle_mount: str = "approle"
    vault_token: str | None = None

    mcp_registry_url: str = "https://registry.modelcontextprotocol.io"

    session_cookie_secure: bool = False
    session_idle_timeout_seconds: int = _DEFAULT_IDLE_TIMEOUT_SECONDS

    @field_validator("cors_origins", mode="before")
    @classmethod
    def _split_cors_origins(cls, value: Any) -> Any:
        """Split a comma-separated ``CORS_ORIGINS`` string into a stripped list."""
        if isinstance(value, str):
            return [origin.strip() for origin in value.split(",")]
        return value

    @field_validator("session_idle_timeout_seconds", mode="before")
    @classmethod
    def _fallback_idle_timeout(cls, value: Any) -> Any:
        """Fall back to the default timeout on an unset or unparseable value.

        Mirrors the previous ``os.getenv`` + ``try/except ValueError`` behavior:
        a missing, empty, or non-integer value silently falls back rather than
        failing validation.
        """
        if value is None or value == "":
            return _DEFAULT_IDLE_TIMEOUT_SECONDS
        try:
            return int(value)
        except (TypeError, ValueError):
            return _DEFAULT_IDLE_TIMEOUT_SECONDS


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Return the process-wide cached :class:`Settings` singleton."""
    return Settings()
