"""FastAPI dependency factories for singletons, database sessions, and repositories.

This package groups the application's dependency-injection wiring by concern:

- :mod:`dependencies.context` — request-scoped helpers and ``APP_NAME``
- :mod:`dependencies.singletons` — LRU-cached process-wide singletons
- :mod:`dependencies.repository` — per-request repositories and the DB session
- :mod:`dependencies.service` — per-request services (use cases)

All public ``*Dep`` aliases, factory functions, and ``APP_NAME`` are re-exported
here so callers can keep importing from ``dependencies`` directly.
"""

from .auth import (
    CSRF_COOKIE_NAME,
    CSRF_HEADER_NAME,
    SESSION_COOKIE_NAME,
    CurrentUserDep,
    CurrentUserIdDep,
    get_current_user,
    get_current_user_id,
    verify_csrf,
)
from .context import (
    APP_NAME,
    ApiMetaDep,
    FilterDep,
    FilterParams,
    PaginationDep,
    PaginationParams,
    SortDep,
    SortParams,
    build_api_meta,
    parse_filters,
    parse_sort,
)
from .repository import (
    AgentSkillRepositoryDep,
    ApprovalRepositoryDep,
    AuthSessionRepositoryDep,
    DBSessionDep,
    MCPServerRepositoryDep,
    NotificationRepositoryDep,
    SecretRepositoryDep,
    UserAvatarRepositoryDep,
    UserRepositoryDep,
    WorkflowRepositoryDep,
    WorkflowSessionRepositoryDep,
    WorkflowTaskRepositoryDep,
    get_agent_skill_repository,
    get_approval_repository,
    get_auth_session_repository,
    get_mcp_server_repository,
    get_notification_repository,
    get_secret_repository,
    get_user_avatar_repository,
    get_user_repository,
    get_workflow_repository,
    get_workflow_session_repository,
    get_workflow_task_repository,
)
from .service import (
    AgentSkillServiceDep,
    ApprovalServiceDep,
    AuthServiceDep,
    MCPRegistryServiceDep,
    MCPServerServiceDep,
    NotificationServiceDep,
    SecretResolverDep,
    SecretServiceDep,
    UserAvatarServiceDep,
    UserServiceDep,
    WorkflowServiceDep,
    WorkflowSessionServiceDep,
    WorkflowTaskServiceDep,
    get_agent_skill_service,
    get_approval_service,
    get_auth_service,
    get_mcp_registry_service,
    get_mcp_server_service,
    get_notification_service,
    get_secret_resolver,
    get_secret_service,
    get_user_avatar_service,
    get_user_service,
    get_workflow_service,
    get_workflow_session_service,
    get_workflow_task_service,
)
from .singletons import (
    AgentRegistryDep,
    SecretCipherDep,
    SessionServiceDep,
    SkillManagerDep,
    VaultClientDep,
    get_agent_registry,
    get_secret_cipher,
    get_session_service,
    get_skill_manager,
    get_vault_client,
)

__all__ = [
    "APP_NAME",
    "CSRF_COOKIE_NAME",
    "CSRF_HEADER_NAME",
    "SESSION_COOKIE_NAME",
    "AgentRegistryDep",
    "AgentSkillRepositoryDep",
    "AgentSkillServiceDep",
    "ApiMetaDep",
    "ApprovalRepositoryDep",
    "ApprovalServiceDep",
    "AuthServiceDep",
    "AuthSessionRepositoryDep",
    "CurrentUserDep",
    "CurrentUserIdDep",
    "DBSessionDep",
    "FilterDep",
    "FilterParams",
    "MCPRegistryServiceDep",
    "MCPServerRepositoryDep",
    "MCPServerServiceDep",
    "NotificationRepositoryDep",
    "NotificationServiceDep",
    "PaginationDep",
    "PaginationParams",
    "SecretCipherDep",
    "SecretRepositoryDep",
    "SecretResolverDep",
    "SecretServiceDep",
    "SessionServiceDep",
    "SortDep",
    "SortParams",
    "SkillManagerDep",
    "VaultClientDep",
    "UserAvatarRepositoryDep",
    "UserAvatarServiceDep",
    "UserRepositoryDep",
    "UserServiceDep",
    "WorkflowRepositoryDep",
    "WorkflowServiceDep",
    "WorkflowSessionRepositoryDep",
    "WorkflowSessionServiceDep",
    "WorkflowTaskRepositoryDep",
    "WorkflowTaskServiceDep",
    "build_api_meta",
    "get_agent_registry",
    "get_agent_skill_repository",
    "get_agent_skill_service",
    "get_approval_repository",
    "get_approval_service",
    "get_auth_service",
    "get_auth_session_repository",
    "get_current_user",
    "get_current_user_id",
    "get_mcp_registry_service",
    "get_mcp_server_repository",
    "get_mcp_server_service",
    "get_notification_repository",
    "get_notification_service",
    "get_secret_cipher",
    "get_secret_repository",
    "get_secret_resolver",
    "get_secret_service",
    "get_session_service",
    "get_skill_manager",
    "get_vault_client",
    "get_user_avatar_repository",
    "get_user_avatar_service",
    "get_user_repository",
    "get_user_service",
    "get_workflow_repository",
    "get_workflow_service",
    "get_workflow_session_repository",
    "get_workflow_session_service",
    "get_workflow_task_repository",
    "get_workflow_task_service",
    "parse_filters",
    "parse_sort",
    "verify_csrf",
]
