"""initial schema

Revision ID: 3baf7438a170
Revises:
Create Date: 2026-07-11 17:01:54.600774

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3baf7438a170"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("display_name", name="uq_tenants_display_name"),
        sa.UniqueConstraint("name", name="uq_tenants_name"),
        # created_by/updated_by -> users.id FKs are added below via
        # batch_alter_table, once "users" exists: tenants and users have a
        # circular FK dependency (every table's created_by/updated_by points
        # at users.id, while users.tenant_id points back at tenants.id), and
        # SQLite cannot resolve a forward-referenced FK inside CREATE TABLE
        # except for self-references.
    )
    op.create_index(
        "ix_tenants_display_name", "tenants", ["display_name"], unique=False
    )
    op.create_index("ix_tenants_name", "tenants", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("avatar_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "roles",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "avatar_config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            ondelete="RESTRICT",
            name="fk_users_tenant_id",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "username", name="uq_users_tenant_id_username"
        ),
        sa.CheckConstraint(
            "tenant_id IS NULL OR CAST(roles AS TEXT) NOT LIKE '%\"super_admin\"%'",
            name="ck_users_super_admin_no_tenant",
        ),
        sa.CheckConstraint(
            "tenant_id IS NOT NULL OR CAST(roles AS TEXT) LIKE '%\"super_admin\"%' "
            "OR id = '00000000-0000-0000-0000-000000000000'",
            name="ck_users_non_super_admin_requires_tenant",
        ),
        sa.CheckConstraint(
            "CAST(roles AS TEXT) NOT LIKE '%\"super_admin\"%' "
            "OR CAST(roles AS TEXT) = '[\"super_admin\"]'",
            name="ck_users_super_admin_exclusive",
        ),
    )
    op.create_index(
        "ix_users_tenant_id_username", "users", ["tenant_id", "username"], unique=False
    )
    op.create_index(
        "ix_users_username_platform_scoped",
        "users",
        ["username"],
        unique=True,
        postgresql_where=sa.text("tenant_id IS NULL"),
        sqlite_where=sa.text("tenant_id IS NULL"),
    )
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        # SQLite's batch mode rebuilds the table and requires every
        # constraint to have an explicit name (unlike a plain CREATE TABLE,
        # where these two FKs are left unnamed elsewhere in this file).
        batch_op.create_foreign_key(
            "fk_tenants_created_by",
            "users",
            ["created_by"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_tenants_updated_by",
            "users",
            ["updated_by"],
            ["id"],
            ondelete="RESTRICT",
        )
    op.create_table(
        "system_settings",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("app_base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("smtp_enabled", sa.Boolean(), nullable=False),
        sa.Column("smtp_host", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("smtp_port", sa.Integer(), nullable=False),
        sa.Column(
            "smtp_security",
            sa.Enum("none", "starttls", "ssl", name="smtpsecurity"),
            nullable=False,
        ),
        sa.Column("smtp_username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("smtp_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("smtp_from_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("smtp_from_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        # Makes "exactly one row" a database invariant rather than a
        # convention: the id is pinned to models.system_settings's
        # SYSTEM_SETTINGS_ID, so a second row cannot be inserted.
        sa.CheckConstraint(
            "id = '00000000-0000-0000-0000-000000000001'",
            name="ck_system_settings_singleton",
        ),
    )
    op.create_table(
        "mcp_certificate_authorities",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("common_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("certificate_pem", Text(), nullable=False),
        sa.Column("private_key_encrypted", Text(), nullable=False),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=False),
        sa.Column("not_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Partial unique index rather than a plain one: retired roots keep their
    # rows (the certificates they signed must stay verifiable) but only one may
    # be active. This is also what makes generate-the-root-on-first-use safe on
    # multiple replicas -- the loser of the race gets an IntegrityError and
    # re-reads instead of minting a second root.
    op.create_index(
        "uq_mcp_certificate_authorities_active",
        "mcp_certificate_authorities",
        ["active"],
        unique=True,
        postgresql_where=sa.text("active"),
        sqlite_where=sa.text("active"),
    )
    op.create_table(
        "agent_skills",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "repo_auth_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "repo_auth_username", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "sync_status",
            sa.Enum("pending", "ready", "failed", name="skillsyncstatus"),
            nullable=False,
        ),
        sa.Column("sync_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("commit_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_agent_skills_tenant_id_name"),
    )
    op.create_index(
        "ix_agent_skills_tenant_id_name",
        "agent_skills",
        ["tenant_id", "name"],
        unique=False,
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("csrf_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_auth_sessions_token_hash"),
    )
    op.create_index(
        "ix_auth_sessions_token_hash", "auth_sessions", ["token_hash"], unique=False
    )
    op.create_table(
        "impersonation_events",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "impersonator_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("target_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["impersonator_id"],
            ["users.id"],
            ondelete="RESTRICT",
            name="fk_impersonation_events_impersonator_id",
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
            ondelete="RESTRICT",
            name="fk_impersonation_events_target_user_id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_impersonation_events_impersonator_id_ended_at",
        "impersonation_events",
        ["impersonator_id", "ended_at"],
        unique=False,
    )
    op.create_index(
        "ix_impersonation_events_target_user_id",
        "impersonation_events",
        ["target_user_id"],
        unique=False,
    )
    op.create_table(
        "mcp_servers",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "transport",
            sa.Enum("streamable_http", "stdio", name="mcptransport"),
            nullable=False,
        ),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "headers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "command",
            sa.Enum("npx", "uvx", name="mcpcommand"),
            nullable=True,
        ),
        sa.Column(
            "args",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "env",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_mcp_servers_tenant_id_name"),
    )
    op.create_index(
        "ix_mcp_servers_tenant_id_name",
        "mcp_servers",
        ["tenant_id", "name"],
        unique=False,
    )
    op.create_table(
        "mcp_tool_mocks",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mcp_server_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "responses",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["mcp_server_id"], ["mcp_servers.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "name", name="uq_mcp_tool_mocks_tenant_id_name"
        ),
    )
    op.create_index(
        "ix_mcp_tool_mocks_mcp_server_id",
        "mcp_tool_mocks",
        ["mcp_server_id"],
        unique=False,
    )
    op.create_index(
        "ix_mcp_tool_mocks_tenant_id_name",
        "mcp_tool_mocks",
        ["tenant_id", "name"],
        unique=False,
    )
    op.create_table(
        "secrets",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("type", sa.Enum("local", "vault", name="secrettype"), nullable=False),
        sa.Column(
            "entries",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("vault_mount", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("vault_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_secrets_tenant_id_name"),
    )
    op.create_index(
        "ix_secrets_tenant_id_name", "secrets", ["tenant_id", "name"], unique=False
    )
    op.create_table(
        "user_avatars",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_user_avatars_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_user_avatars_user_id"),
    )
    op.create_table(
        "workflows",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "generated_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("agent_skill_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "agent_skill_commit_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "generating",
                "draft",
                "failed",
                "published",
                "modified",
                name="workflowstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "generation_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_skill_id"], ["agent_skills.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_workflows_tenant_id_name"),
    )
    op.create_index(
        "ix_workflows_tenant_id_name", "workflows", ["tenant_id", "name"], unique=False
    )
    op.create_index(
        "ix_workflows_session_id", "workflows", ["session_id"], unique=False
    )
    op.create_table(
        "workflow_task_templates",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workflow_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workflow_task_templates_workflow_id",
        "workflow_task_templates",
        ["workflow_id"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_task_templates_tenant_id",
        "workflow_task_templates",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "workflow_task_template_dependencies",
        sa.Column("template_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("depends_on_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.CheckConstraint(
            "template_id <> depends_on_id",
            name="ck_workflow_task_template_dependency_no_self_loop",
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_id"], ["workflow_task_templates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["template_id"], ["workflow_task_templates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("template_id", "depends_on_id"),
    )
    op.create_index(
        "ix_workflow_task_template_dependencies_depends_on_id",
        "workflow_task_template_dependencies",
        ["depends_on_id"],
        unique=False,
    )
    op.create_table(
        "workflow_task_template_tool_bindings",
        sa.Column("template_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mcp_server_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requires_input_approval", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mcp_server_id"], ["mcp_servers.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["template_id"], ["workflow_task_templates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("template_id", "mcp_server_id", "tool_name"),
    )
    op.create_index(
        "ix_workflow_task_template_tool_bindings_mcp_server_id",
        "workflow_task_template_tool_bindings",
        ["mcp_server_id"],
        unique=False,
    )
    op.create_table(
        "workflow_published_versions",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workflow_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "templates",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_id", name="uq_workflow_published_versions_workflow_id"
        ),
    )
    op.create_index(
        "ix_workflow_published_versions_tenant_id",
        "workflow_published_versions",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "workflow_executions",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("agent_skill_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "agent_skill_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "agent_skill_repo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "agent_skill_repo_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "agent_skill_commit_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("initiator_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workflow_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column(
            "tool_mocks",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "tool_mock_calls",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "completed",
                "failed",
                name="workflowexecutionstatus",
            ),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["initiator_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workflow_executions_session_id",
        "workflow_executions",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_executions_tenant_id",
        "workflow_executions",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_executions_tenant_id_status",
        "workflow_executions",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_executions_tenant_id_created_at",
        "workflow_executions",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "approval_request",
                "execution_completed",
                "workflow_draft_ready",
                "workflow_generation_failed",
                name="notificationtype",
            ),
            nullable=False,
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "workflow_execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("workflow_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("link", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_notifications_user_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"],
            ["workflow_executions.id"],
            name="fk_notifications_workflow_execution_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name="fk_notifications_workflow_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notifications_user_id", "notifications", ["user_id"], unique=False
    )
    op.create_index(
        "ix_notifications_workflow_execution_id",
        "notifications",
        ["workflow_execution_id"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_workflow_id",
        "notifications",
        ["workflow_id"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_tenant_id",
        "notifications",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "outbound_emails",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notification_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("to_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sending",
                "sent",
                "failed",
                name="outboundemailstatus",
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
            name="fk_outbound_emails_notification_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_outbound_emails_status_next_attempt_at",
        "outbound_emails",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_index(
        "ix_outbound_emails_notification_id",
        "outbound_emails",
        ["notification_id"],
        unique=False,
    )
    op.create_index(
        "ix_outbound_emails_tenant_id",
        "outbound_emails",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "workflow_tasks",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "workflow_execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "completed",
                "failed",
                "skipped",
                name="workflowtaskstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "error_kind",
            sa.Enum(
                "api_error",
                "timeout",
                "script_error",
                "invalid_input",
                "permission_denied",
                "rejected",
                "other",
                name="taskerrorkind",
            ),
            nullable=True,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"], ["workflow_executions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workflow_tasks_workflow_execution_id",
        "workflow_tasks",
        ["workflow_execution_id"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_tasks_tenant_id",
        "workflow_tasks",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_tasks_tenant_id_status",
        "workflow_tasks",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_table(
        "approvals",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "approved", "rejected", "returned", name="approvalstatus"
            ),
            nullable=False,
        ),
        sa.Column("response", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "workflow_execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "workflow_task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("approver", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "approver_group_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "approved_calls",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approver"],
            ["users.id"],
            name="fk_approvals_approver",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name="fk_approvals_decided_by",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"],
            ["workflow_executions.id"],
            name="fk_approvals_workflow_execution_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_task_id"],
            ["workflow_tasks.id"],
            name="fk_approvals_workflow_task_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        # approver_group_id -> user_groups.id is added later, once
        # "user_groups" exists (see the batch_alter_table call right after
        # that table is created below): user_groups is created after
        # approvals in this file, and a plain CREATE TABLE FK cannot
        # forward-reference a table that doesn't exist yet.
        sa.CheckConstraint(
            "approver IS NULL OR approver_group_id IS NULL",
            name="ck_approvals_single_destination",
        ),
    )
    op.create_index("ix_approvals_approver", "approvals", ["approver"], unique=False)
    op.create_index(
        "ix_approvals_approver_group_id",
        "approvals",
        ["approver_group_id"],
        unique=False,
    )
    op.create_index(
        "ix_approvals_workflow_execution_id",
        "approvals",
        ["workflow_execution_id"],
        unique=False,
    )
    op.create_index(
        "ix_approvals_workflow_task_id", "approvals", ["workflow_task_id"], unique=False
    )
    op.create_index("ix_approvals_tenant_id", "approvals", ["tenant_id"], unique=False)
    op.create_index(
        "ix_approvals_tenant_id_status",
        "approvals",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_approvals_tenant_id_decided_at",
        "approvals",
        ["tenant_id", "decided_at"],
        unique=False,
    )
    op.create_table(
        "message_meta",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "workflow_execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("workflow_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("adk_event_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sender_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "workflow_task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.CheckConstraint(
            "(workflow_execution_id IS NULL) <> (workflow_id IS NULL)",
            name="ck_message_meta_single_parent",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["users.id"],
            name="fk_message_meta_sender_user_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"],
            ["workflow_executions.id"],
            name="fk_message_meta_workflow_execution_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name="fk_message_meta_workflow_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_task_id"],
            ["workflow_tasks.id"],
            name="fk_message_meta_workflow_task_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_execution_id",
            "adk_event_id",
            name="uq_message_meta_execution_event",
        ),
        sa.UniqueConstraint(
            "workflow_id",
            "adk_event_id",
            name="uq_message_meta_workflow_event",
        ),
    )
    op.create_index(
        "ix_message_meta_sender_user_id",
        "message_meta",
        ["sender_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_message_meta_workflow_execution_id",
        "message_meta",
        ["workflow_execution_id"],
        unique=False,
    )
    op.create_index(
        "ix_message_meta_workflow_id",
        "message_meta",
        ["workflow_id"],
        unique=False,
    )
    op.create_index(
        "ix_message_meta_workflow_task_id",
        "message_meta",
        ["workflow_task_id"],
        unique=False,
    )
    op.create_index(
        "ix_message_meta_tenant_id",
        "message_meta",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "workflow_task_dependencies",
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("depends_on_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.CheckConstraint(
            "task_id <> depends_on_id", name="ck_workflow_task_dependency_no_self_loop"
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_id"], ["workflow_tasks.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["workflow_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "depends_on_id"),
    )
    op.create_index(
        "ix_workflow_task_dependencies_depends_on_id",
        "workflow_task_dependencies",
        ["depends_on_id"],
        unique=False,
    )
    op.create_table(
        "workflow_task_tool_bindings",
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mcp_server_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requires_input_approval", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mcp_server_id"], ["mcp_servers.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["workflow_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "mcp_server_id", "tool_name"),
    )
    op.create_index(
        "ix_workflow_task_tool_bindings_mcp_server_id",
        "workflow_task_tool_bindings",
        ["mcp_server_id"],
        unique=False,
    )
    op.create_table(
        "user_groups",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "roles",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_user_groups_tenant_id_name"),
        sa.CheckConstraint(
            "CAST(roles AS TEXT) NOT LIKE '%\"super_admin\"%'",
            name="ck_user_groups_no_super_admin",
        ),
    )
    op.create_index(
        "ix_user_groups_tenant_id_name",
        "user_groups",
        ["tenant_id", "name"],
        unique=False,
    )
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        # Deferred for the same reason as the tenants/users circular FK
        # above: user_groups now exists, so approver_group_id can finally
        # get its foreign key.
        batch_op.create_foreign_key(
            "fk_approvals_approver_group_id",
            "user_groups",
            ["approver_group_id"],
            ["id"],
            ondelete="RESTRICT",
        )
    op.create_table(
        "user_group_members",
        sa.Column("group_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["user_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
    )
    op.create_index(
        "ix_user_group_members_user_id",
        "user_group_members",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "tags",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "color",
            sa.Enum(
                "mint",
                "teal",
                "cyan",
                "indigo",
                "violet",
                "rose",
                "amber",
                "slate",
                name="tagcolor",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_tags_tenant_id_name"),
    )
    op.create_index(
        "ix_tags_tenant_id_name",
        "tags",
        ["tenant_id", "name"],
        unique=False,
    )
    for link_table, owner_table in (
        ("secret_tags", "secrets"),
        ("workflow_tags", "workflows"),
        ("mcp_server_tags", "mcp_servers"),
        ("agent_skill_tags", "agent_skills"),
    ):
        op.create_table(
            link_table,
            sa.Column(
                "resource_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            ),
            sa.Column("tag_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.ForeignKeyConstraint(
                ["resource_id"], [f"{owner_table}.id"], ondelete="CASCADE"
            ),
            sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("resource_id", "tag_id"),
        )
        op.create_index(
            f"ix_{link_table}_tag_id",
            link_table,
            ["tag_id"],
            unique=False,
        )
    # Created last: it references approvals, workflow_tasks,
    # workflow_executions, tenants, and mcp_certificate_authorities, so every
    # one of those tables has to exist first.
    op.create_table(
        "mcp_tool_certificates",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # Named ``grant_kind`` rather than ``grant``: ``GRANT`` is a reserved
        # word in SQL, and the check constraint below has to spell it unquoted.
        sa.Column(
            "grant_kind",
            sa.Enum("approval", "initiator", name="certificategrant"),
            nullable=False,
        ),
        # Nullable: an initiator grant speaks for no approval at all.
        sa.Column("approval_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("granted_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "workflow_execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "workflow_task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("ca_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("serial_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("certificate_pem", Text(), nullable=False),
        sa.Column("private_key_encrypted", Text(), nullable=False),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=False),
        sa.Column("not_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "revocation_reason",
            sa.Enum(
                "task_finished",
                "superseded_by_approval",
                name="revocationreason",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["approval_id"], ["approvals.id"], ondelete="CASCADE"),
        # RESTRICT, matching the audit user FKs: the person a grant is
        # attributed to cannot be hard-deleted out from under the certificate.
        sa.ForeignKeyConstraint(["granted_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"], ["workflow_executions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workflow_task_id"], ["workflow_tasks.id"], ondelete="CASCADE"
        ),
        # RESTRICT: a root that signed a certificate must stay readable, or the
        # certificate it signed can no longer be verified.
        sa.ForeignKeyConstraint(
            ["ca_id"], ["mcp_certificate_authorities.id"], ondelete="RESTRICT"
        ),
        # ``approval_id`` and ``grant_kind`` say the same thing two ways, so the
        # table refuses a row where they disagree.
        sa.CheckConstraint(
            "(grant_kind = 'approval' AND approval_id IS NOT NULL)"
            " OR (grant_kind = 'initiator' AND approval_id IS NULL)",
            name="ck_mcp_tool_certificates_grant_shape",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # One *live* certificate per approval and task. Keyed on the pair because
    # an approval covers the task it names plus every task downstream of it up
    # to the next approval, and each of those is granted its own certificate
    # when it starts. Partial rather than a plain unique constraint so a revoked
    # certificate stays in the table: the audit trail has to keep showing that
    # authority was granted and when it stopped counting, and a re-issue after
    # revocation must still be possible.
    op.create_index(
        "uq_mcp_tool_certificates_live",
        "mcp_tool_certificates",
        ["approval_id", "workflow_task_id"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
        sqlite_where=sa.text("revoked_at IS NULL"),
    )
    # And one *live* initiator grant per task. Separate from the index above
    # because ``approval_id`` is NULL on every one of those rows, and NULLs
    # never collide in a unique index on either dialect.
    op.create_index(
        "uq_mcp_tool_certificates_live_initiator",
        "mcp_tool_certificates",
        ["workflow_task_id"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL AND approval_id IS NULL"),
        sqlite_where=sa.text("revoked_at IS NULL AND approval_id IS NULL"),
    )
    op.create_index(
        "ix_mcp_tool_certificates_tenant_id", "mcp_tool_certificates", ["tenant_id"]
    )
    op.create_index(
        "ix_mcp_tool_certificates_workflow_execution_id",
        "mcp_tool_certificates",
        ["workflow_execution_id"],
    )
    op.create_index(
        "ix_mcp_tool_certificates_workflow_task_id",
        "mcp_tool_certificates",
        ["workflow_task_id"],
    )
    op.create_index(
        "ix_mcp_tool_certificates_serial_number",
        "mcp_tool_certificates",
        ["serial_number"],
        unique=True,
    )
    # Audit of MCP tool-call decisions. Deliberately carries no foreign key to
    # workflow_executions / workflow_tasks: CASCADE would delete the evidence
    # with the run and RESTRICT would make an audited run undeletable. See
    # models/mcp_tool_invocation.py.
    op.create_table(
        "mcp_tool_invocations",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "workflow_execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "workflow_task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "certificate_serial", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("approval_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mcp_server_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("allowed", "denied", name="mcpauditdecision"),
            nullable=False,
        ),
        sa.Column("denial_reason", Text(), nullable=True),
        sa.Column(
            "arguments_digest", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("signature", Text(), nullable=True),
        sa.Column("nonce", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_mcp_tool_invocations_tenant_id_created_at",
        "mcp_tool_invocations",
        ["tenant_id", "created_at"],
    )
    op.create_index(
        "ix_mcp_tool_invocations_workflow_execution_id",
        "mcp_tool_invocations",
        ["workflow_execution_id"],
    )
    op.create_index(
        "ix_mcp_tool_invocations_certificate_serial",
        "mcp_tool_invocations",
        ["certificate_serial"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_mcp_tool_invocations_certificate_serial",
        table_name="mcp_tool_invocations",
    )
    op.drop_index(
        "ix_mcp_tool_invocations_workflow_execution_id",
        table_name="mcp_tool_invocations",
    )
    op.drop_index(
        "ix_mcp_tool_invocations_tenant_id_created_at",
        table_name="mcp_tool_invocations",
    )
    op.drop_table("mcp_tool_invocations")
    op.drop_index(
        "uq_mcp_tool_certificates_live_initiator", table_name="mcp_tool_certificates"
    )
    op.drop_index("uq_mcp_tool_certificates_live", table_name="mcp_tool_certificates")
    op.drop_index(
        "ix_mcp_tool_certificates_serial_number", table_name="mcp_tool_certificates"
    )
    op.drop_index(
        "ix_mcp_tool_certificates_workflow_task_id", table_name="mcp_tool_certificates"
    )
    op.drop_index(
        "ix_mcp_tool_certificates_workflow_execution_id",
        table_name="mcp_tool_certificates",
    )
    op.drop_index(
        "ix_mcp_tool_certificates_tenant_id", table_name="mcp_tool_certificates"
    )
    op.drop_table("mcp_tool_certificates")
    for link_table in (
        "agent_skill_tags",
        "mcp_server_tags",
        "workflow_tags",
        "secret_tags",
    ):
        op.drop_index(f"ix_{link_table}_tag_id", table_name=link_table)
        op.drop_table(link_table)
    op.drop_index("ix_tags_tenant_id_name", table_name="tags")
    op.drop_table("tags")
    op.drop_index("ix_user_group_members_user_id", table_name="user_group_members")
    op.drop_table("user_group_members")
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        # Must go before user_groups is dropped below: this FK references it.
        batch_op.drop_constraint("fk_approvals_approver_group_id", type_="foreignkey")
    op.drop_index("ix_user_groups_tenant_id_name", table_name="user_groups")
    op.drop_table("user_groups")
    op.drop_index(
        "ix_workflow_published_versions_tenant_id",
        table_name="workflow_published_versions",
    )
    op.drop_table("workflow_published_versions")
    op.drop_index(
        "ix_workflow_task_template_tool_bindings_mcp_server_id",
        table_name="workflow_task_template_tool_bindings",
    )
    op.drop_table("workflow_task_template_tool_bindings")
    op.drop_index(
        "ix_workflow_task_template_dependencies_depends_on_id",
        table_name="workflow_task_template_dependencies",
    )
    op.drop_table("workflow_task_template_dependencies")
    op.drop_index(
        "ix_workflow_task_templates_workflow_id",
        table_name="workflow_task_templates",
    )
    op.drop_index(
        "ix_workflow_task_templates_tenant_id",
        table_name="workflow_task_templates",
    )
    op.drop_table("workflow_task_templates")
    op.drop_index(
        "ix_workflow_task_tool_bindings_mcp_server_id",
        table_name="workflow_task_tool_bindings",
    )
    op.drop_table("workflow_task_tool_bindings")
    op.drop_index(
        "ix_workflow_task_dependencies_depends_on_id",
        table_name="workflow_task_dependencies",
    )
    op.drop_table("workflow_task_dependencies")
    op.drop_index("ix_message_meta_workflow_task_id", table_name="message_meta")
    op.drop_index("ix_message_meta_workflow_id", table_name="message_meta")
    op.drop_index("ix_message_meta_workflow_execution_id", table_name="message_meta")
    op.drop_index("ix_message_meta_sender_user_id", table_name="message_meta")
    op.drop_index("ix_message_meta_tenant_id", table_name="message_meta")
    op.drop_table("message_meta")
    op.drop_index("ix_approvals_workflow_task_id", table_name="approvals")
    op.drop_index("ix_approvals_workflow_execution_id", table_name="approvals")
    op.drop_index("ix_approvals_approver", table_name="approvals")
    op.drop_index("ix_approvals_tenant_id", table_name="approvals")
    op.drop_index("ix_approvals_tenant_id_status", table_name="approvals")
    op.drop_index("ix_approvals_tenant_id_decided_at", table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(
        "ix_workflow_tasks_workflow_execution_id", table_name="workflow_tasks"
    )
    op.drop_index("ix_workflow_tasks_tenant_id", table_name="workflow_tasks")
    op.drop_index("ix_workflow_tasks_tenant_id_status", table_name="workflow_tasks")
    op.drop_table("workflow_tasks")
    op.drop_index("ix_outbound_emails_tenant_id", table_name="outbound_emails")
    op.drop_index("ix_outbound_emails_notification_id", table_name="outbound_emails")
    op.drop_index(
        "ix_outbound_emails_status_next_attempt_at", table_name="outbound_emails"
    )
    op.drop_table("outbound_emails")
    op.drop_index("ix_notifications_workflow_id", table_name="notifications")
    op.drop_index("ix_notifications_workflow_execution_id", table_name="notifications")
    op.drop_index("ix_notifications_user_id", table_name="notifications")
    op.drop_index("ix_notifications_tenant_id", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_workflow_executions_session_id", table_name="workflow_executions")
    op.drop_index("ix_workflow_executions_tenant_id", table_name="workflow_executions")
    op.drop_index(
        "ix_workflow_executions_tenant_id_status", table_name="workflow_executions"
    )
    op.drop_index(
        "ix_workflow_executions_tenant_id_created_at", table_name="workflow_executions"
    )
    op.drop_table("workflow_executions")
    op.drop_index("ix_workflows_session_id", table_name="workflows")
    op.drop_index("ix_workflows_tenant_id_name", table_name="workflows")
    op.drop_table("workflows")
    op.drop_table("user_avatars")
    op.drop_index("ix_secrets_tenant_id_name", table_name="secrets")
    op.drop_table("secrets")
    op.drop_index("ix_mcp_tool_mocks_tenant_id_name", table_name="mcp_tool_mocks")
    op.drop_index("ix_mcp_tool_mocks_mcp_server_id", table_name="mcp_tool_mocks")
    op.drop_table("mcp_tool_mocks")
    op.drop_index("ix_mcp_servers_tenant_id_name", table_name="mcp_servers")
    op.drop_table("mcp_servers")
    op.drop_index(
        "ix_impersonation_events_target_user_id", table_name="impersonation_events"
    )
    op.drop_index(
        "ix_impersonation_events_impersonator_id_ended_at",
        table_name="impersonation_events",
    )
    op.drop_table("impersonation_events")
    op.drop_index("ix_auth_sessions_token_hash", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index("ix_agent_skills_tenant_id_name", table_name="agent_skills")
    op.drop_table("agent_skills")
    op.drop_index(
        "uq_mcp_certificate_authorities_active",
        table_name="mcp_certificate_authorities",
    )
    op.drop_table("mcp_certificate_authorities")
    op.drop_table("system_settings")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("fk_users_tenant_id", type_="foreignkey")
        batch_op.drop_constraint("uq_users_tenant_id_username", type_="unique")
        batch_op.drop_index("ix_users_tenant_id_username")
        batch_op.drop_index("ix_users_username_platform_scoped")
        # Both CHECK constraints reference tenant_id, so they must be dropped
        # before the column itself or SQLite's batch-mode table rebuild fails
        # with "no such column: tenant_id" while recreating the table.
        batch_op.drop_constraint("ck_users_super_admin_no_tenant", type_="check")
        batch_op.drop_constraint(
            "ck_users_non_super_admin_requires_tenant", type_="check"
        )
        batch_op.drop_column("tenant_id")
    op.drop_index("ix_tenants_name", table_name="tenants")
    op.drop_index("ix_tenants_display_name", table_name="tenants")
    op.drop_table("tenants")
    op.drop_table("users")
    # ### end Alembic commands ###
