import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The manual's sidebar is hand-written rather than autogenerated so the reading
 * order is explicit: what A2Flow is, how to get it running, the concepts behind
 * it, a guide per feature, then the architecture and day-two operations.
 */
const sidebars: SidebarsConfig = {
  manualSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/quick-start',
        'getting-started/docker-compose',
        'getting-started/llm-configuration',
        'getting-started/demo-data',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/terminology',
        'concepts/authentication',
        'concepts/authorization',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/workflows',
        'guides/workflow-executions',
        'guides/approvals',
        'guides/agent-skills',
        'guides/mcp-servers',
        'guides/tool-mocks',
        'guides/secrets',
        'guides/tags',
        'guides/users-and-groups',
        'guides/notifications',
        'guides/system-settings',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: ['architecture/overview', 'architecture/database'],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/configuration',
        'operations/deployment',
        'operations/scaling',
        'operations/metrics',
      ],
    },
  ],
};

export default sidebars;
